//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Final_Schedule
    {
        public int ID { get; set; }
        public int ID_Professors { get; set; }
        public int ID_Courses { get; set; }
        public int NumClass { get; set; }
        public int NumRoom { get; set; }
        public System.DateTime DateOfClass { get; set; }
        public int ClassLeft { get; set; }
    
        public virtual Final_Courses Final_Courses { get; set; }
        public virtual Final_Professors Final_Professors { get; set; }
    }
}
